# Generated by Django 5.0 on 2023-12-07 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital_auth_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="pincode",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.OneToOneField(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="hospital_auth_app.usertypes",
            ),
        ),
    ]
