# Generated by Django 5.0 on 2023-12-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital_auth_app", "0002_alter_user_pincode_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(default="Patient", max_length=10),
        ),
        migrations.DeleteModel(
            name="UserTypes",
        ),
    ]
