# Generated by Django 5.0 on 2023-12-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital_auth_app", "0004_user_is_admin_user_is_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorsToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
