# Generated by Django 5.0 on 2023-12-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital_auth_app", "0005_doctorstoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=models.TextField(blank=True, null=True),
        ),
    ]
