# Generated by Django 5.0 on 2023-12-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital_blog_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="is_draft",
            field=models.BooleanField(default=False),
        ),
    ]
