# Generated by Django 5.0 on 2023-12-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital_blog_app", "0002_blog_created_at_blog_is_draft"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="blog_slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
