# Generated by Django 5.0 on 2024-01-05 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital_appointment_app", "0001_initial"),
        ("hospital_auth_app", "0002_specialityofdoctors_doctordetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_id",
                to="hospital_auth_app.doctordetail",
            ),
        ),
    ]
